langchain4j:
  open-ai:
    chat-model:
      api-key: demo # only for test purpose
      model-name: gpt-4o-mini

logging.level.dev.langchain4j: DEBUG

dataSource:
  url: 'jdbc:h2:mem:test;DB_CLOSE_DELAY=-1'
  user: 'sa'
  password: 'sa'
  script: 'sql/IMDBdatasetimport.sql'
